## Vectorisation
---


In [2]:
import numpy as np
import time

In [3]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [4]:
tic = time.time()
c = np.dot(a.T, b)
toc = time.time()
print('Vector time:',(toc - tic) * 1000, 'ms')

Vector time: 12.28475570678711 ms


In [5]:
z = 0.0
tic = time.time()
for i in range(1000000):
    z += a[i]*b[i]
toc = time.time()
print('Loop time:', (toc - tic) * 1000, 'ms')

Loop time: 431.6680431365967 ms


In [6]:
c,z

(250224.87298034254, 250224.87298033596)

## More Vectorization Examples

---

## Vectorizing Logistic Regression
---

## Broadcasting in Python
---

In [50]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [52]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [59]:
100 * A / cal.reshape(1,4)

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [61]:
100 * A / cal.T

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [62]:
100 * A / cal

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

## A note on python/numpy vectors
---

In [79]:
a = np.random.randn(5)
a

array([ 0.00529262, -0.19069098, -0.4680707 , -0.586457  ,  0.00593568])

In [80]:
a.shape

(5,)

In [81]:
a.T

array([ 0.00529262, -0.19069098, -0.4680707 , -0.586457  ,  0.00593568])

In [82]:
np.dot(a, a.T)

0.5994482852570058

In [83]:
a = np.random.randn(5,1)
a

array([[ 0.40960529],
       [-0.52189307],
       [ 1.01679989],
       [-0.3024033 ],
       [ 1.42430053]])

In [84]:
a.shape

(5, 1)

In [88]:
a.T

array([[ 0.40960529, -0.52189307,  1.01679989, -0.3024033 ,  1.42430053]])

In [87]:
np.dot(a, a.T)

array([[ 0.1677765 , -0.21377017,  0.41648662, -0.12386599,  0.58340104],
       [-0.21377017,  0.27237238, -0.53066082,  0.15782219, -0.74333258],
       [ 0.41648662, -0.53066082,  1.03388202, -0.30748364,  1.44822863],
       [-0.12386599,  0.15782219, -0.30748364,  0.09144776, -0.43071318],
       [ 0.58340104, -0.74333258,  1.44822863, -0.43071318,  2.028632  ]])

In [89]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)

In [90]:
b

array([[-0.52916008],
       [-0.87732661]])

In [91]:
a

array([[-1.3585676 , -0.22500839,  1.45513131],
       [ 0.20201002, -0.25578071,  0.64718771]])

In [92]:
c = a + b

In [95]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)

c = a * b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [96]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [99]:

c

array([[ 0.12160244,  0.87882861,  0.00157172],
       [ 0.05763057, -0.50716409, -0.29629644],
       [ 0.49111081,  0.38863105, -0.20080211]])

In [103]:
np.exp(1)

2.718281828459045

In [106]:
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + math.exp(-x))
    ### END CODE HERE ###
    
    return s

In [107]:
basic_sigmoid(3)

0.9525741268224334